### ISSUE TITLE
implement dshell install

### ISSUE THREAD

**Issue by bsutton** [bsutton/dshell#12]
To install dshell a user must run pub activate journey to get dshell fully functional there are some house keeping functions required.

To make these easier we should implement a dshell command:

Dshell install

Dshell install should perform the following actions.

Create the dshell settings directory.
Write a version file into ~/.dshell
Copy the dshell exe into /use/bin
Copy third into ~/.dshell/templates
Display a nice message with some instructions or a getting started link.

Update the read me on how to install.

**Comment by jonas-jonas** [comment]
So, I think as you're using pub.dev to publish this, its way of globally activating packages should be used. For me, I do have the ~/.pub-cache/bin folder in my path. That might seem inelegant, but for now it's the way to go.

As Dart is compilable to native (as you do already, I think) we should offer 
- an APT repository for ubuntu
- a DNF repository for fedora
- maybe a homebrew entry for macos 
- and a way for windows user (might be an installer, or just a choco entry)

This way we can distribute a native version of the package via the OSes package managers and users don't have to hassle with pub.

For now, I'd suggest to keep using the `pub global` way as current users are most likely familiar with Dart (and subsequently pub). I would add a section to the README to describe the way of installing (including how to set up the path).

**Comment by bsutton** [comment]
I see where you coming from and it makes sense to deleliver a native install.

My concern is that (in my experience) building an apt installer is a major undertaking mainly due to that lack of quality doco.
Snap may also be a better option.  I've built a couple of snaps and the are easier than apt but still a pain.

So my concern is that in the short term we deliver a clunky install experience.

If we use the suggested dshell install command then we can deliver a clean install experince immediately and the work towards native installers when we have the resources.
The native installers could also use the dshell install command so we don't have to write a native install for each of them.

Upgrades to the native installers would then not be needed as all the work could be fine in dart.


Thoughts?

**Comment by bsutton** [comment]
I've implemented the basic dshell install so have a crack at a native installer.
