### ISSUE TITLE
Rofi and dshell

### ISSUE THREAD

**Issue by ram535** [bsutton/dshell#37]
When running this command in the terminal, works as expected.

```
ls | rofi -dmenu -i 
```

But when I run this command in a dshell script.

```
'ls | rofi -dmenu -i'.run;
```

It throw this error.

```
Unhandled exception:
The command [ls | rofi -dmenu -i] failed with exitCode: 2
#0      waitForEx (package:dshell/src/util/waitForEx.dart:35:7)
#1      RunnableProcess.processUntilExit (package:dshell/src/util/runnable_process.dart:85:5)
#2      Run.run (package:dshell/src/functions/run.dart:35:16)
#3      run (package:dshell/src/functions/run.dart:22:11)
#4      StringAsProcess.run (package:dshell/src/util/string_as_process.dart:25:19)
#5      main (file:///home/last/.dshell/cache/home/last/bin/scripts/rofi_bangs.project/rofi_bangs.dart:13:25)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Thanks in advance.

**Comment by bsutton** [comment]
You miss have quotes around each command.

'ls' | 'rofi -dmenu -i'.run;

**Comment by ram535** [comment]
Oops, Yeah I missed those. I should pay more attention next time.

I made the modification but now I get this error.

```
../../.dshell/cache/home/last/bin/scripts/rofi_bangs.project/rofi_bangs.dart:8:27: Error: This expression has type 'void' and can't be used.
  'ls' | 'rofi -dmenu -i'.run;
                          ^
```

I hope I did not miss something obvious.

**Comment by bsutton** [comment]
OK, so my mistake.
There were actually to problems here.
1) the | operator doesn't support run.
Or I should say didn't as I've just pushed an update (1.0.38) that now supports run.
2) the second problem was a flaw in my documentation and a requirement I had forgotten about.

You need to change the line to:
('ls' | 'rofi -dmenu -i').run;

The parentheses are required to change the precedence as we need to force the | operator to take precedence of the run operation.

So:
1) add the parentheses
2) run 
pub global activate dshell
3) run 
dshell clean <name of your script>
And with any luck that should solve your problem.

**Comment by ram535** [comment]
It worked. Thank you.
