### ISSUE TITLE
A option that just print the output to the console

### ISSUE THREAD

**Issue by ram535** [bsutton/dshell#41]
Don't you think it would be a good idea to just have an option that prints the output to the console?

Yesterday when I was first playing with dshell, I did this:

```
'ls'.run;
```

Expecting to see the output. But then I read more in the documentation and I saw that I have to do this if I want to see the output.

```
'ls.'forEach((x)=>print(x));
```

And my first thought was 'that's is kind of ugly if I just want to see the output printed in the console'.
Maybe to have something like this would be better if we just want to see the output in the console:

```
'ls'.output;
```
or
```
'ls'.print;
```

or

```
'ls'.run.output;
```

or 

```
'ls'.run.print;
```

Or something similar.

**Comment by bsutton** [comment]
Sorry this is actually a bug.

'ls'.run should print to stderr and stderr.
I've just published 1.0.40 which fixes this issue.

I'm still grappling with the best way to right unit tests that check output to stdout and stderr which is why there isn't a unit test for this scenario.
