### ISSUE TITLE
doesn't work on OSX

### ISSUE THREAD

**Issue by RandalSchwartz** [bsutton/dshell#47]
Doesn’t work for me:
```
dshell: Exception occured: The file at /Users/merlyn/.bashrc does not exists of type ReadException
dshell: Stacktrace: read.dart : Read.read : 39
read.dart : read : 25
install.dart : InstallCommand.isCompletionInstalled : 168
install.dart : InstallCommand.addCompletion : 153
install.dart : InstallCommand.run : 88
command_line_runner.dart : CommandLineRunner.process : 81
entry_point.dart : EntryPoint._parseCmdLine : 37
entry_point.dart : EntryPoint.process : 31
dshell.dart : DShell.run : 9
dshell.dart : main : 4



```

**Comment by bsutton** [comment]
try the latest build in which I've added a fix for the above

pub global activate dshell 1.1.0-dev.2

**Comment by bsutton** [comment]
I've just pushed 1.1.0. to pub.dev.
I actually found a secondary issue around your reported problem which the release also fixes.

Give it a try and let me know if you have problems.
I will close this issue for now but feel free to re-open if its not fixed.
