### ISSUE TITLE
copy's overwrite flag is not respected

### ISSUE THREAD

**Issue by renatoathaydes** [bsutton/dshell#52]
**Describe the bug**

Hi! It seems you forgot to pass on the `overwrite` flag in the [copy function](https://github.com/bsutton/dshell/blob/master/lib/src/functions/copy.dart#L23).

Cheers.

**Comment by bsutton** [comment]
Good pickup.

I will have fixed in the next couple of days.

**Comment by bsutton** [comment]
I've just pushed the fix. I''m in the middle of backgrounding the pub get
when running dshell create so will be a few days before I'm ready to
publish a new release.

**Comment by bsutton** [comment]
Released as part 1.3.0.
