### ISSUE TITLE
Don't use .run as a getter

### ISSUE THREAD

**Issue by enyo** [bsutton/dshell#63]
Thanks for the tool. It looks good and some of the API is really clever.
I think that using `.run` as a getter is a big design flaw though. Getters should not have side effects and invoking a getter multiple times should not do anything.
I think that this needs to be changed to a function. There is no reason for this to be a getter.

**Comment by bsutton** [comment]
I guess I would see this somewhat differently.

Getters are syntax sugar and whilst in a normal code base I would probably
agree with you that generally getters should have no side effects.

But I only take that as a general guideline.

There are plenty of cases where having a getter with a side effect is
useful - e.g. updating a last accessed field.

In this case the use is obvious and the fact it has a side effect is also
obvious.

If you a writing getters where people don't expect a side effect then I
would agree, we have a serious design flaw.

One thing I've learnt after a lot of years coding: don't be too
religious about coding practices.
Its far more important that the api is obvious, easy to use and does what
people would reasonably expect.

It's when an api does the unexpected that we have a real problem.

Either way, I appreciate you taking the time to give feedback.

**Comment by enyo** [comment]
Thanks for your reply @bsutton 

The reason I think this is a bad idea is not only because it is against best practice but also because it fundamentally misuses a language feature for a purely aesthetic reason.

Functions in dart are invoked with `()`. But a developer might just dislike this kind of syntax, and decide that it's "cooler" to invoke functions without parentheses in general.

So that code could look like this:

```dart
get startServer => _startServerInternally();
String serverStatus => _getServerStatus();

main() {
  startServer;
  final status = serverStatus;
}
```

You see how this code becomes a horror to read? That is not how the syntax of the language works, and decisions like these make it confusing for people to learn a language or framework.

**Comment by bsutton** [comment]
I think you are confusing what could be done with what has been done.
You example nicely highlights poor use of a getter that results in code that is hard to understand.

I don't believe that the run getter results in confusion and feedback (whilst at this point limited) seems to support my view.
I have considered changing run to a method but for a different reason. That being extensibility. Using a method would allow me to add named arguments to run to allow a user greater control over how run executes the command.
At this point I'm inclined to leave it alone and provide other methods (like start()) which allow greater control.

The first rule of a library is that it should be simple to understand and use. Elegance is a nice to have.
My use of run as a getter providers some elegance so fits into the nice to have category.
So it's not necessary but it I like the syntax and I don't believe its confusing.

My view of design patterns is that they are tools and guidelines rather than laws. I'm always careful when I ignore common design patterns but I like to think I have enough experince to know when they can be ignored:)

**Comment by enyo** [comment]
Thanks for your elaborate answer.

> Elegance is a nice to have.

I would say that the problem of this statement is, that what people find elegant is very subjective, so it's hard to argue against or for.

You accused me of confusing what could be done with what can be done; but why do you feel that my example highlights poor use and your's is elegant? Let me reduce the example to a simple `run` getter:

```dart
get run => _runMyCode();
main() { run; }
```

- What would you say is the defining difference that makes this poor use and less elegant than having a `run` getter on a String?

- Are you in favour of dart dropping parenthesis in general when invoking methods that don't required arguments from dart? If not, why is your use case different?

* * *

I think that your example of why you considered switching it back to a method highlights my disdain for this liberal use of a getter: you have used a language feature that is meant for something else and gave up functionality for a visual effect. The API of this library is now stuck with the `.run` method never being able to accept any arguments unless you make a breaking change to the library or use other names as a workaround.

* * *

> My view of design patterns is that they are tools and guidelines rather than laws. I'm always careful when I ignore common design patterns but I like to think I have enough experince to know when they can be ignored:)

I agree with you on that, and I'm sure you have enough experience. These decisions are rarely objective and concepts like elegance are subjective perceptions so it's completely normal to have different opinions on it.

I feel that consistency is one of the most important aspect of a good library and ecosystem and departing from consistency rules must be justified with very good reasons other than personal preference over what constitutes elegance.

That's what I've always liked about dart, that they have a strong style guide, and an opinionated dart formatter that is not supposed to be configurable. You might think it's more elegant to use 2 spaces instead of a tab, but it doesn't really matter, because someone else might think the opposite. It's just important that everyone follows the same rules otherwise reading code from someone else becomes tiresome and more complicated than it should be even though it might appear more elegant. (I know that not everyone agrees with me on the lack of configurability of `dartfmt` as well so... 🤷‍♂)

Thanks for the discussion and providing the reasoning behind this decision! I don't expect we'll change each others minds but that doesn't matter :)

**Comment by bsutton** [comment]
closed.
