### ISSUE TITLE
SocketException: Failed to create datagram socket (OS Error: Can't assign requested address, errno = 49), address = 127.0.0.172, port = 63424 of type DShellException

### ISSUE THREAD

**Issue by geooooo** [bsutton/dshell#70]
## Run 
`dshell create script.dart`
or
`./script.dart`

```
# script.dart
#!/usr/bin/env dshell
import 'package:dshell/dshell.dart';
void main() {
  print('Hello World');
}
```

## Actual error in both cases:
Exception occured: SocketException: Failed to create datagram socket (OS Error: Can't assign requested address, errno = 49), address = 127.0.0.172, port = 63424 of type DShellException
Stacktrace: with_lock.dart : NamedLock.withLock.<anonymous closure> : 124
zone.dart : runZoned : 1505
with_lock.dart : NamedLock.withLock : 96
virtual_project.dart : VirtualProject.build : 297
run.dart : RunCommand.run : 44
command_line_runner.dart : CommandLineRunner.process : 81
entry_point.dart : EntryPoint._parseCmdLine : 36
entry_point.dart : EntryPoint.process : 30
dshell.dart : DShell.run : 9
dshell.dart : main : 4

## Doctor:
```
$ dshell doctor
Dshell version    1.8.12

OS                macos
OS Version        Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Path separator    /

dart version      2.7.1

dshell path       /<HOME>/.pub-cache/bin/dshell
dart exe path     /usr/local/bin/dart
dart path         /usr/local/bin/dart                      which: /usr/local/bin/dart
dart2Native path  /usr/local/bin/dart2native               which: /usr/local/bin/dart2native

pub get path      /usr/local/bin/pub                       which: /usr/local/bin/pub
Pub cache         /<HOME>/.pub-cache
Package Config    Not Passed

PATH
                  /<HOME>/.nvm/versions/node/v8.9.4/bin
                  /<HOME>/.rvm/gems/ruby-2.6.3/bin
                  /<HOME>/.rvm/gems/ruby-2.6.3@global/bin
                  /<HOME>/.rvm/rubies/ruby-2.6.3/bin
                  /usr/local/bin
                  /usr/bin
                  /bin
                  /usr/sbin
                  /sbin
                  /<HOME>/.rvm/bin
                  /<HOME>/.pub-cache/bin

$SHELL            /bin/zsh
True SHELL        unknown
Shell Start Scrip Not Found

Dart location(s)
                  /usr/local/bin/dart

Permissions

.dshell/dependencies.yaml
  dshell          dshell: ^1.0.0
  args            args: ^1.5.2
  path            path: ^1.6.4
```

**Comment by bsutton** [comment]
So it looks like osx doesn't expose the full set of loop backs.

I've just pushed 1.8.13-dev.1 which has a fix for this.

Run
pub global activate dshell 1.8.13-dev.1

and try again.

**Comment by geooooo** [comment]
Works, thanks !

**Comment by bsutton** [comment]
Yury,
glad to hear it works.

I don't currently have access to a mac so I'm quite interested in any
feedback/changes that you have.

If you are interested in getting involved in the project that would be
great as well.

Brett
